using Microsoft.Extensions.Configuration;

namespace ManiaAPI.ManiaPlanetAPI.Tests.Integration;

public class ManiaPlanetAPITests
{
    [Fact]
    public async Task TestVariousRequests()
    {
        var configuration = new ConfigurationBuilder()
            .AddUserSecrets<AutoGeneratedProgram>()
            .Build();

        var clientId = configuration.GetValue<string>("ClientId") ?? throw new Exception("ClientId is required");
        var clientSecret = configuration.GetValue<string>("ClientSecret") ?? throw new Exception("ClientSecret is required");

        var api = new ManiaPlanetAPI();

        await api.AuthorizeAsync(clientId, clientSecret);

        var servers = await api.SearchOnlineServersAsync(
            titleUids: ["TMLagoon@nadeo", "TMStadium@nadeo"], 
            environments: ["Stadium", "Lagoon"], 
            search: "lol", 
            zone: "World|Europe");

        var titles = await api.SearchTitlesAsync(filters: ["trackmania", "solo"], orderBy: "lastUpdate");
        var title = await api.GetTitleByUidAsync(titles.First().Uid);
        var scripts = await api.GetTitleScriptsAsync(titles.First().Uid);
        var zones = await api.GetZonesAsync();

        // cuz tested on dedicated server, it should not pass
        await Assert.ThrowsAsync<ManiaPlanetAPIResponseException>(() => api.GetDedicatedAccountsAsync());
        await Assert.ThrowsAsync<ManiaPlanetAPIResponseException>(() => api.GetEmailAsync());
        await Assert.ThrowsAsync<ManiaPlanetAPIResponseException>(() => api.GetMapsAsync());
        await Assert.ThrowsAsync<ManiaPlanetAPIResponseException>(() => api.GetPlayerAsync());
        await Assert.ThrowsAsync<ManiaPlanetAPIResponseException>(() => api.GetTitlesAsync());
    }
}
